### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by cjfrick13** [araxiaonline/mod-auctionator#19]
Unable to compile from source code with Azerothcore's latest commits. Tried with liyunfan1223's fork of azerothcore-wotlk for playerbots and Auctionator is causing compiling errors. Tried with latest commit of the original azerothcore-wotlk and getting the exact same compiling errors.

![ACCompileErrors](https://github.com/user-attachments/assets/2913644d-ade3-498e-b7fd-83a9bb3b91b2)
![ACErrors](https://github.com/user-attachments/assets/cfa5affc-9ce2-4439-acaf-ea87a1f96fcb)

**Comment by jaylittle** [comment]
I'm guessing this commit broke it: https://github.com/azerothcore/azerothcore-wotlk/commit/21f86d1c3c0d48ca8f31c6d6f29005fe492a9a2e

**Comment by james-huston** [comment]
@jaylittle Looking into this, will have a fix up in a bit.

**Comment by jaylittle** [comment]
> @jaylittle Looking into this, will have a fix up in a bit.

Thank you so much!  I updated everything and compilation went off without a hitch.  Will play with it more in a little bit and make sure the plugin is actually working, thanks!
