### ISSUE TITLE
v0.3 - Worldserver is not starting up fully after module installation

### ISSUE THREAD

**Issue by icemansparks** [araxiaonline/mod-auctionator#3]
After installation, new CMake and build, my worldserver now is now closing itself at

`AzerothCore rev. c9ab7e7e9678 2023-10-17 08:40:55 +0000 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...
[Auctionator]: Auctionator initializing...`

The errorlog is empty but there is a crash file created in /crashes which i will add here as well.
Removing the module solves the problem and the server is running just as before.
[c9ab7e7e9678_worldserver.exe_[17-10_20-25-11].txt](https://github.com/araxiaonline/mod-auctionator/files/12942874/c9ab7e7e9678_worldserver.exe_.17-10_20-25-11.txt)

**Comment by james-huston** [comment]
Looks like you are running on Windows, is that correct? I have not tested there but will try to do that in the next day or 2.

Also did you make any changes to the config? Can you post the config you are using here please?

Thanks!

**Comment by james-huston** [comment]
And are you using AzerothCore or a different fork? What version/branch are you running?

**Comment by icemansparks** [comment]
I tested the install with the latest AzerothCore official master branch with the commits from yesterday.
Yes, I am running it under Windows 10 64bit.

The only changes in the config that I made were adjustments of the character guid and ID, as well as trying to disable the module when it not worked (which seems to have no effect on server startup).

[auctionator_mod.txt](https://github.com/araxiaonline/mod-auctionator/files/13031107/auctionator_mod.txt)

**Comment by james-huston** [comment]
I think I see the issue (my terrible c++ code, this is my first project) and I am not sure why this works at all. I can't fix/test it until later tonight but I will try to get a fix out this evening.

**Comment by icemansparks** [comment]
Changing the line order of the suggested lines allowed me to complile and start the server again.
Auctions also seem to be created correctly as far as i can tell.

**Comment by james-huston** [comment]
@icemansparks Thank you for the PR, merged and release v0.4 cut. This mod is very early in it's life so please feel free to submit feature requests and PRs. Thanks!
