### ISSUE TITLE
[Suggestion] Readme correction

### ISSUE THREAD

**Issue by noisiver** [araxiaonline/mod-auctionator#5]
The SQL queries provided in the readme, related to performing a clean setup, are wrong. I don't think I have to explain what I'm talking about but just in case, *acore_world.mod_acore_characters.item_instance* is not a table.

I also don't think you should include the name of the database in the queries but instead tell the user they have to run it against their characters database. This is something that has been corrected multiple times with AzerothCore because it produces errors for enough people, say if they're not using the "standard" database names.

In case you want to keep it as simple as possible, I would instead suggest doing something like this. There is no reason to use aliases if you have absolutely no use for them.

```sql
DELETE FROM `item_instance` WHERE `guid` IN (SELECT `itemguid` FROM `auctionhouse`);
DELETE FROM `auctionhouse`;
```

**Comment by rv-jhuston** [comment]
Both of these are correct, I will get updates going for them. Thank you @noisiver !
